In [ ]:
import pandas as pd

# Data processing

### Task 1

#### Calculate Loyalty Points

In [ ]:
df = pd.read_excel("Test.xlsx", sheet_name="Data. Transactions")

In [ ]:
df.head()

In [ ]:
for i in range(len(df)):
    if df["Service Group"][i] ==  "supermarket":
        df["Loyalty Points"][i] = (df["GMV"][i] * 1) / 1000
    elif df["Service Group"][i] ==  "data":
        df["Loyalty Points"][i] = (df["GMV"][i] * 10) / 1000
    elif df["Service Group"][i] ==  "cvs":
        df["Loyalty Points"][i] = (df["GMV"][i] * 1) / 1000
    elif df["Service Group"][i] ==  "marketplace":
        df["Loyalty Points"][i] = (df["GMV"][i] * 1) / 1000
    elif df["Service Group"][i] ==  "Coffee chains and Milk tea":
        df["Loyalty Points"][i] = (df["GMV"][i] * 1) / 1000
    elif df["Service Group"][i] ==  "Offline Beverage":
        df["Loyalty Points"][i] = (df["GMV"][i] * 1) / 1000

In [ ]:
df["Loyalty Points"] = df["Loyalty Points"].astype("int")

In [ ]:
df.head()

In [ ]:
df.to_excel("Final.xlsx", sheet_name= "Data. Transactions")

#### Identify User's Rank Name

In [ ]:
df1 = pd.read_excel("Test.xlsx", sheet_name="Loyalty Ranking")

In [ ]:
df1 = df1.drop_duplicates().groupby("User_id").sum().reset_index()

In [ ]:
df1.head()

In [ ]:
for i in range(len(df1)):
    if df1["Calculated_points"][i] >= 1 and df1["Calculated_points"][i] <= 999:
        df1["Rank_name"][i] = "STANDARD"
    elif df1["Calculated_points"][i] >= 1000 and df1["Calculated_points"][i] <= 1999:
        df1["Rank_name"][i] = "SILVER"
    elif df1["Calculated_points"][i] >= 2000 and df1["Calculated_points"][i] <= 4999:
        df1["Rank_name"][i] = "GOLD"
    else:
        df1["Rank_name"][i] = "DIAMOND"

In [ ]:
df1.head()

In [ ]:
df1["Rank_name"].value_counts()

In [ ]:
df1.to_excel("Final1.xlsx", sheet_name= "Loyalty Ranking")

### Task 2

#### Identify User's Rank Name for each Transaction

In [123]:
df = pd.read_excel("Test.xlsx", sheet_name= "Draft cashback")

In [124]:
df.head()

,DATE,Order_id,NEWVERTICAL_Merchant,MerchantID,User_id,GMV,Service Group,Loyalty Points,Rank_name,$cashback
0,2022-02-01,20510379115,Airtime,30,32983630,14000,data,140,NaN,NaN
1,2022-02-01,20514342785,Airtime,30,3560552,10000,data,100,NaN,NaN
2,2022-02-01,20502357355,Airtime,30,52261329,28000,data,280,NaN,NaN
3,2022-02-01,20514894447,Airtime,30,45221505,20000,data,200,NaN,NaN
4,2022-02-01,20498110250,Airtime,30,32983630,5000,data,50,NaN,NaN

In [125]:
df1 = pd.read_excel("Test.xlsx", sheet_name= "Draft pair value")

In [126]:
df1.head()

   User_id_1 Rank_name_1
0     136825    STANDARD
1     162483    STANDARD
2     199215    STANDARD
3     298202    STANDARD
4     321062    STANDARD

In [127]:
data_dict = dict(zip(df1.User_id_1, df1.Rank_name_1))
data_dict

{136825: 'STANDARD',
 162483: 'STANDARD',
 199215: 'STANDARD',
 298202: 'STANDARD',
 321062: 'STANDARD',
 414676: 'SILVER',
 422520: 'STANDARD',
 449519: 'STANDARD',
 489606: 'SILVER',
 519699: 'STANDARD',
 541332: 'STANDARD',
 542712: 'STANDARD',
 624465: 'STANDARD',
 800810: 'STANDARD',
 858014: 'SILVER',
 858250: 'STANDARD',
 863945: 'STANDARD',
 891873: 'STANDARD',
 911881: 'STANDARD',
 922900: 'GOLD',
 964714: 'SILVER',
 981084: 'STANDARD',
 988787: 'STANDARD',
 1018832: 'GOLD',
 1179780: 'STANDARD',
 1193693: 'STANDARD',
 1209335: 'STANDARD',
 1251478: 'STANDARD',
 1260485: 'STANDARD',
 1299518: 'STANDARD',
 1311608: 'STANDARD',
 1377674: 'STANDARD',
 1438464: 'STANDARD',
 1457828: 'STANDARD',
 1491642: 'STANDARD',
 1502572: 'GOLD',
 1586756: 'STANDARD',
 1604661: 'STANDARD',
 1671305: 'STANDARD',
 1726700: 'STANDARD',
 1737058: 'STANDARD',
 1737580: 'STANDARD',
 1763075: 'STANDARD',
 1768953: 'DIAMOND',
 1822405: 'STANDARD',
 1844333: 'STANDARD',
 1922772: 'STANDARD',
 1967042: 'STANDARD',
 1976295: 'STANDARD',
 2049557: 'STANDARD',
 2117259: 'STANDARD',
 2354050: 'SILVER',
 2360528: 'STANDARD',
 2376156: 'STANDARD',
 2492654: 'STANDARD',
 2656449: 'STANDARD',
 2720965: 'STANDARD',
 2729106: 'STANDARD',
 2735686: 'STANDARD',
 2735892: 'DIAMOND',
 2866961: 'STANDARD',
 2906056: 'STANDARD',
 2908312: 'STANDARD',
 2981624: 'STANDARD',
 3135230: 'STANDARD',
 3173126: 'SILVER',
 3177428: 'STANDARD',
 3226890: 'STANDARD',
 3412954: 'STANDARD',
 3438840: 'STANDARD',
 3448660: 'STANDARD',
 3460665: 'STANDARD',
 3525210: 'STANDARD',
 3560552: 'SILVER',
 3598604: 'STANDARD',
 3738885: 'STANDARD',
 3780696: 'STANDARD',
 3935464: 'STANDARD',
 3961871: 'STANDARD',
 4023686: 'STANDARD',
 4066193: 'STANDARD',
 4132641: 'STANDARD',
 4172409: 'STANDARD',
 4183724: 'SILVER',
 4248562: 'SILVER',
 4266481: 'STANDARD',
 4275352: 'STANDARD',
 4290681: 'SILVER',
 4301401: 'SILVER',
 4349216: 'STANDARD',
 4350750: 'STANDARD',
 4388433: 'GOLD',
 4422122: 'STANDARD',
 4438273: 'STANDARD',
 4514651: 'STANDARD',
 4562906: 'SILVER',
 4599920: 'STANDARD',
 4757068: 'STANDARD',
 4762521: 'GOLD',
 4805456: 'STANDARD',
 4951822: 'STANDARD',
 5128291: 'STANDARD',
 5147567: 'STANDARD',
 5392128: 'STANDARD',
 5393691: 'STANDARD',
 5475712: 'DIAMOND',
 5496117: 'STANDARD',
 5521230: 'STANDARD',
 5545483: 'SILVER',
 5550592: 'SILVER',
 5657795: 'STANDARD',
 5718736: 'STANDARD',
 5720027: 'STANDARD',
 5779403: 'STANDARD',
 5910722: 'STANDARD',
 6009444: 'STANDARD',
 6017244: 'STANDARD',
 6023262: 'STANDARD',
 6089172: 'STANDARD',
 6144145: 'STANDARD',
 6236019: 'GOLD',
 6289139: 'STANDARD',
 6327814: 'STANDARD',
 6342026: 'STANDARD',
 6400063: 'SILVER',
 6483809: 'STANDARD',
 6568658: 'STANDARD',
 6575123: 'STANDARD',
 6618736: 'STANDARD',
 6729543: 'GOLD',
 6967518: 'STANDARD',
 7145613: 'STANDARD',
 7161548: 'STANDARD',
 7184863: 'STANDARD',
 7197250: 'STANDARD',
 7302790: 'STANDARD',
 7360828: 'STANDARD',
 7451161: 'SILVER',
 7534839: 'STANDARD',
 7545640: 'STANDARD',
 7596385: 'STANDARD',
 7596437: 'STANDARD',
 7625126: 'STANDARD',
 7660892: 'SILVER',
 7680583: 'STANDARD',
 7752869: 'STANDARD',
 7868598: 'STANDARD',
 7879146: 'STANDARD',
 7906398: 'STANDARD',
 7979133: 'STANDARD',
 8036046: 'STANDARD',
 8041218: 'STANDARD',
 8076209: 'SILVER',
 8081102: 'DIAMOND',
 8152025: 'STANDARD',
 8199608: 'STANDARD',
 8226911: 'STANDARD',
 8273513: 'STANDARD',
 8332769: 'SILVER',
 8375713: 'STANDARD',
 8413409: 'STANDARD',
 8450872: 'STANDARD',
 8500513: 'STANDARD',
 8507165: 'STANDARD',
 8552827: 'SILVER',
 8691088: 'STANDARD',
 8821539: 'STANDARD',
 8883595: 'GOLD',
 8929951: 'GOLD',
 9018733: 'GOLD',
 9223450: 'SILVER',
 9225080: 'STANDARD',
 9244015: 'STANDARD',
 9343442: 'STANDARD',
 9377242: 'STANDARD',
 9622392: 'STANDARD',
 9658247: 'STANDARD',
 9691514: 'STANDARD',
 10056218: 'STANDARD',
 10154027: 'STANDARD',
 10156282: 'STANDARD',
 10184635: 'GOLD',
 10247812: 'STANDARD',
 10249777: 'SILVER',
 10266510: 'SILVER',
 10295158: 'STANDARD',
 10309537: 'STANDARD',
 10318393: 'STANDARD',
 10365941: 'STANDARD',
 10368512: 'STANDARD',
 10382002: 'STANDARD',
 10528435: 'STANDARD',
 10636051: 'SILVER',
 10642188: 'STANDARD',
 10986565: 'STANDARD',
 11187745: 'STANDARD',
 11238876: 'STANDARD',
 11355891: 'STANDARD',
 11386030: 'STANDARD',
 11497022: 'STANDARD',
 11627750: 'STANDARD',
 11822657: 'STANDARD',
 11832106: 'STANDARD',
 11928872: 'STANDARD',
 11965822: 'STANDARD',
 12015962: 'STANDARD',
 12052308: 'STANDARD',
 12132892: 'STANDARD',
 12149602: 'SILVER',
 12175821: 'STANDARD',
 12229364: 'DIAMOND',
 12280683: 'STANDARD',
 12343883: 'GOLD',
 12387519: 'STANDARD',
 12453498: 'STANDARD',
 12913787: 'STANDARD',
 13077353: 'STANDARD',
 13282724: 'STANDARD',
 13351423: 'SILVER',
 13637611: 'SILVER',
 13646297: 'STANDARD',
 13648553: 'STANDARD',
 13689935: 'SILVER',
 13793954: 'STANDARD',
 13818542: 'STANDARD',
 13873204: 'STANDARD',
 13888947: 'STANDARD',
 13901094: 'STANDARD',
 13906844: 'STANDARD',
 13920492: 'DIAMOND',
 13927876: 'STANDARD',
 13952847: 'STANDARD',
 14070882: 'STANDARD',
 14177580: 'STANDARD',
 14203877: 'STANDARD',
 14283264: 'STANDARD',
 14476093: 'STANDARD',
 14479257: 'STANDARD',
 14537664: 'SILVER',
 14708046: 'STANDARD',
 14725339: 'STANDARD',
 14734714: 'STANDARD',
 14827392: 'STANDARD',
 14854145: 'SILVER',
 14856665: 'STANDARD',
 14922074: 'STANDARD',
 15007239: 'GOLD',
 15029205: 'STANDARD',
 15049477: 'STANDARD',
 15098063: 'SILVER',
 15210026: 'STANDARD',
 15251602: 'STANDARD',
 15269604: 'STANDARD',
 15274790: 'STANDARD',
 15477467: 'STANDARD',
 15486118: 'STANDARD',
 15533775: 'STANDARD',
 15594661: 'STANDARD',
 15685672: 'STANDARD',
 15708058: 'STANDARD',
 15786154: 'STANDARD',
 15811964: 'STANDARD',
 15842820: 'STANDARD',
 15873250: 'SILVER',
 15886868: 'STANDARD',
 15978313: 'STANDARD',
 16097999: 'STANDARD',
 16225321: 'STANDARD',
 16287663: 'STANDARD',
 16411700: 'STANDARD',
 16645874: 'SILVER',
 16736014: 'STANDARD',
 16738125: 'SILVER',
 16785710: 'STANDARD',
 16872391: 'STANDARD',
 16883847: 'STANDARD',
 17144057: 'STANDARD',
 17165854: 'GOLD',
 17177675: 'STANDARD',
 17399360: 'STANDARD',
 17492688: 'STANDARD',
 17536560: 'STANDARD',
 17676899: 'STANDARD',
 17806985: 'STANDARD',
 17844849: 'STANDARD',
 17846869: 'STANDARD',
 17888209: 'DIAMOND',
 17918183: 'STANDARD',
 17938338: 'STANDARD',
 17953439: 'STANDARD',
 17955011: 'STANDARD',
 17991892: 'STANDARD',
 17993642: 'STANDARD',
 18067798: 'STANDARD',
 18172351: 'STANDARD',
 18220615: 'STANDARD',
 18256776: 'STANDARD',
 18291312: 'STANDARD',
 18352379: 'GOLD',
 18359947: 'STANDARD',
 18366044: 'STANDARD',
 18515714: 'STANDARD',
 18523781: 'STANDARD',
 18576275: 'STANDARD',
 18623237: 'SILVER',
 18671367: 'STANDARD',
 18702813: 'STANDARD',
 18794568: 'STANDARD',
 18865734: 'STANDARD',
 18940992: 'STANDARD',
 18946234: 'STANDARD',
 18958008: 'STANDARD',
 18965882: 'STANDARD',
 19009446: 'STANDARD',
 19092563: 'STANDARD',
 19140964: 'STANDARD',
 19261998: 'STANDARD',
 19352799: 'STANDARD',
 19400309: 'GOLD',
 19418871: 'STANDARD',
 19471048: 'STANDARD',
 19531556: 'STANDARD',
 19532135: 'STANDARD',
 19678409: 'STANDARD',
 19759538: 'STANDARD',
 19819811: 'STANDARD',
 19835777: 'STANDARD',
 19848242: 'SILVER',
 19888734: 'STANDARD',
 20110383: 'SILVER',
 20113754: 'STANDARD',
 20115148: 'GOLD',
 20116388: 'STANDARD',
 20202165: 'STANDARD',
 20300197: 'SILVER',
 20373723: 'STANDARD',
 20420238: 'SILVER',
 20446921: 'STANDARD',
 20453558: 'STANDARD',
 20459648: 'STANDARD',
 20459704: 'STANDARD',
 20473027: 'SILVER',
 20697823: 'STANDARD',
 20746097: 'STANDARD',
 20758344: 'STANDARD',
 20766579: 'STANDARD',
 20904319: 'STANDARD',
 20920211: 'STANDARD',
 20929790: 'SILVER',
 21057573: 'STANDARD',
 21233335: 'STANDARD',
 21359157: 'STANDARD',
 21375357: 'STANDARD',
 21410974: 'STANDARD',
 21438567: 'STANDARD',
 21449157: 'STANDARD',
 21533239: 'STANDARD',
 21752575: 'GOLD',
 21821467: 'STANDARD',
 22090975: 'SILVER',
 22163734: 'STANDARD',
 22216336: 'STANDARD',
 22257992: 'STANDARD',
 22425558: 'GOLD',
 22428356: 'STANDARD',
 22456808: 'STANDARD',
 22542310: 'STANDARD',
 22561180: 'SILVER',
 22621081: 'STANDARD',
 22638767: 'STANDARD',
 22687712: 'STANDARD',
 22725516: 'STANDARD',
 22912981: 'STANDARD',
 22964832: 'STANDARD',
 23000775: 'STANDARD',
 23007450: 'SILVER',
 23229313: 'STANDARD',
 23288875: 'STANDARD',
 23399830: 'STANDARD',
 23433627: 'STANDARD',
 23438678: 'SILVER',
 23524151: 'STANDARD',
 23564123: 'SILVER',
 23723178: 'GOLD',
 23772905: 'STANDARD',
 23781103: 'STANDARD',
 23799972: 'SILVER',
 23903360: 'GOLD',
 24042910: 'STANDARD',
 24106786: 'STANDARD',
 24270789: 'STANDARD',
 24370783: 'STANDARD',
 24373403: 'STANDARD',
 24392435: 'STANDARD',
 24397797: 'SILVER',
 24405063: 'STANDARD',
 24499237: 'STANDARD',
 24549284: 'STANDARD',
 24578439: 'SILVER',
 24618012: 'STANDARD',
 24707620: 'STANDARD',
 24754671: 'STANDARD',
 24801663: 'STANDARD',
 24837425: 'SILVER',
 24972188: 'STANDARD',
 25032173: 'SILVER',
 25035626: 'STANDARD',
 25045859: 'STANDARD',
 25216022: 'STANDARD',
 25247429: 'STANDARD',
 25265450: 'STANDARD',
 25428726: 'STANDARD',
 25575368: 'DIAMOND',
 25714977: 'GOLD',
 25733890: 'STANDARD',
 25746218: 'STANDARD',
 25787061: 'SILVER',
 25801751: 'STANDARD',
 25806792: 'STANDARD',
 25830958: 'STANDARD',
 25993024: 'DIAMOND',
 26005069: 'STANDARD',
 26022343: 'STANDARD',
 26103518: 'STANDARD',
 26137073: 'STANDARD',
 26212620: 'STANDARD',
 26262547: 'STANDARD',
 26360625: 'STANDARD',
 26419409: 'STANDARD',
 26542291: 'STANDARD',
 26549351: 'STANDARD',
 26574979: 'STANDARD',
 26637394: 'DIAMOND',
 26700881: 'STANDARD',
 26728881: 'SILVER',
 26734000: 'STANDARD',
 26796320: 'STANDARD',
 26938014: 'STANDARD',
 26968526: 'STANDARD',
 27018672: 'DIAMOND',
 27041252: 'STANDARD',
 27137902: 'STANDARD',
 27147134: 'GOLD',
 27202974: 'STANDARD',
 27352107: 'STANDARD',
 27358281: 'STANDARD',
 27400002: 'STANDARD',
 27404233: 'STANDARD',
 27555865: 'STANDARD',
 27696467: 'STANDARD',
 27733452: 'STANDARD',
 27738005: 'STANDARD',
 27772763: 'STANDARD',
 27786041: 'GOLD',
 27802502: 'STANDARD',
 27882170: 'STANDARD',
 27931443: 'STANDARD',
 27962742: 'STANDARD',
 28006611: 'STANDARD',
 28051787: 'GOLD',
 28054557: 'GOLD',
 28057457: 'SILVER',
 28072844: 'STANDARD',
 28103867: 'STANDARD',
 28111507: 'STANDARD',
 28151813: 'STANDARD',
 28158299: 'STANDARD',
 28201330: 'STANDARD',
 28208863: 'SILVER',
 28272013: 'DIAMOND',
 28333908: 'STANDARD',
 28333909: 'STANDARD',
 28355063: 'STANDARD',
 28357777: 'STANDARD',
 28362540: 'STANDARD',
 28386590: 'GOLD',
 28486514: 'STANDARD',
 28507970: 'SILVER',
 28512019: 'STANDARD',
 28563161: 'STANDARD',
 28743087: 'STANDARD',
 28796893: 'STANDARD',
 28800328: 'STANDARD',
 28804388: 'STANDARD',
 28805125: 'STANDARD',
 28841982: 'STANDARD',
 28944155: 'SILVER',
 28971953: 'STANDARD',
 29029358: 'STANDARD',
 29058087: 'STANDARD',
 29141389: 'STANDARD',
 29150216: 'STANDARD',
 29150320: 'STANDARD',
 29332951: 'STANDARD',
 29372079: 'GOLD',
 29423239: 'STANDARD',
 29430575: 'STANDARD',
 29431549: 'STANDARD',
 29449685: 'STANDARD',
 29517131: 'STANDARD',
 29532091: 'SILVER',
 29569506: 'STANDARD',
 29648681: 'STANDARD',
 29651364: 'GOLD',
 29666057: 'STANDARD',
 29885031: 'STANDARD',
 29892307: 'STANDARD',
 29893405: 'GOLD',
 29920882: 'SILVER',
 29925576: 'STANDARD',
 29965540: 'STANDARD',
 29972296: 'STANDARD',
 30006709: 'SILVER',
 30025126: 'STANDARD',
 30032350: 'STANDARD',
 30037832: 'STANDARD',
 30051320: 'STANDARD',
 30052513: 'STANDARD',
 30069471: 'STANDARD',
 30078946: 'GOLD',
 30083381: 'STANDARD',
 30159614: 'DIAMOND',
 30166697: 'STANDARD',
 30239015: 'SILVER',
 30354544: 'STANDARD',
 30358943: 'STANDARD',
 30376307: 'SILVER',
 30382877: 'STANDARD',
 30422095: 'SILVER',
 30457495: 'STANDARD',
 30496277: 'STANDARD',
 30511745: 'STANDARD',
 30543681: 'STANDARD',
 30579161: 'STANDARD',
 30594613: 'STANDARD',
 30614705: 'GOLD',
 30617402: 'STANDARD',
 30625911: 'DIAMOND',
 30640527: 'SILVER',
 30655564: 'STANDARD',
 30683246: 'STANDARD',
 30745002: 'SILVER',
 30750092: 'STANDARD',
 30780275: 'STANDARD',
 30816723: 'STANDARD',
 30871045: 'SILVER',
 30884726: 'STANDARD',
 30908388: 'STANDARD',
 30924175: 'STANDARD',
 30926714: 'STANDARD',
 30978647: 'STANDARD',
 30992452: 'STANDARD',
 31001699: 'STANDARD',
 31058664: 'STANDARD',
 31232341: 'STANDARD',
 31244414: 'DIAMOND',
 31367816: 'STANDARD',
 31384889: 'GOLD',
 31412074: 'DIAMOND',
 31427626: 'STANDARD',
 31449512: 'STANDARD',
 31455923: 'STANDARD',
 31466076: 'GOLD',
 31526697: 'STANDARD',
 31593929: 'STANDARD',
 31637113: 'STANDARD',
 31660579: 'STANDARD',
 31663135: 'STANDARD',
 31698776: 'STANDARD',
 31712063: 'STANDARD',
 31749517: 'STANDARD',
 31799383: 'SILVER',
 31808109: 'STANDARD',
 31831157: 'STANDARD',
 31879224: 'STANDARD',
 31885942: 'STANDARD',
 31912209: 'STANDARD',
 31939329: 'STANDARD',
 31956379: 'STANDARD',
 31958067: 'STANDARD',
 32015781: 'STANDARD',
 32025848: 'STANDARD',
 32032789: 'STANDARD',
 32043301: 'STANDARD',
 32075256: 'STANDARD',
 32086622: 'STANDARD',
 32126310: 'STANDARD',
 32126516: 'STANDARD',
 32148649: 'STANDARD',
 32149867: 'STANDARD',
 32151942: 'STANDARD',
 32155467: 'STANDARD',
 32162282: 'STANDARD',
 32167787: 'STANDARD',
 32173337: 'STANDARD',
 32200127: 'STANDARD',
 32241651: 'SILVER',
 32276351: 'STANDARD',
 32313266: 'STANDARD',
 32404607: 'STANDARD',
 32464073: 'GOLD',
 32494902: 'STANDARD',
 32568024: 'STANDARD',
 32570802: 'STANDARD',
 32601700: 'STANDARD',
 32634798: 'STANDARD',
 32646224: 'STANDARD',
 32649161: 'STANDARD',
 32682576: 'STANDARD',
 32792994: 'STANDARD',
 32832089: 'STANDARD',
 32843779: 'STANDARD',
 32863418: 'SILVER',
 32863480: 'DIAMOND',
 32874728: 'STANDARD',
 32896339: 'STANDARD',
 32946301: 'STANDARD',
 32963958: 'STANDARD',
 32982786: 'STANDARD',
 32983630: 'STANDARD',
 32997148: 'GOLD',
 33011685: 'STANDARD',
 33032803: 'STANDARD',
 33050826: 'STANDARD',
 33062656: 'SILVER',
 33071017: 'STANDARD',
 33071385: 'STANDARD',
 33073905: 'SILVER',
 33100365: 'STANDARD',
 33180415: 'GOLD',
 33201885: 'GOLD',
 33210059: 'STANDARD',
 33210781: 'STANDARD',
 33223974: 'STANDARD',
 33236372: 'STANDARD',
 33236418: 'STANDARD',
 33278221: 'STANDARD',
 33282750: 'STANDARD',
 33295851: 'GOLD',
 33296279: 'STANDARD',
 33298337: 'STANDARD',
 33304969: 'STANDARD',
 33314132: 'STANDARD',
 33335342: 'STANDARD',
 33365728: 'STANDARD',
 33393216: 'STANDARD',
 33435387: 'STANDARD',
 33453644: 'SILVER',
 33494908: 'STANDARD',
 33532278: 'STANDARD',
 33532643: 'STANDARD',
 33545058: 'STANDARD',
 33560737: 'STANDARD',
 33571564: 'STANDARD',
 33582894: 'SILVER',
 33586869: 'STANDARD',
 33594384: 'STANDARD',
 33594748: 'STANDARD',
 33604171: 'STANDARD',
 33643919: 'STANDARD',
 33672039: 'STANDARD',
 33679209: 'STANDARD',
 33686280: 'STANDARD',
 33694877: 'STANDARD',
 33697936: 'STANDARD',
 33708683: 'GOLD',
 33714577: 'STANDARD',
 33716822: 'STANDARD',
 33755096: 'STANDARD',
 33770146: 'STANDARD',
 33838410: 'STANDARD',
 33855379: 'STANDARD',
 33902362: 'STANDARD',
 33906386: 'STANDARD',
 33914639: 'GOLD',
 33938898: 'STANDARD',
 33939917: 'STANDARD',
 33953620: 'STANDARD',
 33989222: 'STANDARD',
 33992121: 'STANDARD',
 33995564: 'STANDARD',
 34033354: 'STANDARD',
 34036988: 'GOLD',
 34040492: 'STANDARD',
 34054063: 'STANDARD',
 34057928: 'STANDARD',
 34063435: 'STANDARD',
 34074561: 'GOLD',
 34083162: 'STANDARD',
 34087995: 'SILVER',
 34093137: 'STANDARD',
 34098938: 'STANDARD',
 34111200: 'STANDARD',
 34112716: 'STANDARD',
 34119819: 'STANDARD',
 34121253: 'STANDARD',
 34130542: 'STANDARD',
 34133569: 'STANDARD',
 34142984: 'STANDARD',
 34152379: 'STANDARD',
 34156916: 'GOLD',
 34158811: 'GOLD',
 34187109: 'GOLD',
 34190345: 'STANDARD',
 34222599: 'STANDARD',
 34223283: 'STANDARD',
 34231873: 'STANDARD',
 34248817: 'STANDARD',
 34251023: 'SILVER',
 34261081: 'STANDARD',
 34289365: 'STANDARD',
 34295116: 'STANDARD',
 34317148: 'STANDARD',
 34367853: 'DIAMOND',
 34368033: 'STANDARD',
 34379760: 'STANDARD',
 34420185: 'STANDARD',
 34453199: 'STANDARD',
 34492726: 'STANDARD',
 34499614: 'SILVER',
 34503457: 'STANDARD',
 34524278: 'SILVER',
 34539424: 'STANDARD',
 34559111: 'STANDARD',
 34601853: 'SILVER',
 34608789: 'STANDARD',
 34713791: 'STANDARD',
 34738186: 'STANDARD',
 34739098: 'STANDARD',
 34760295: 'STANDARD',
 34761467: 'STANDARD',
 34775939: 'STANDARD',
 34793842: 'STANDARD',
 34858224: 'STANDARD',
 34863155: 'SILVER',
 34867397: 'STANDARD',
 34883663: 'STANDARD',
 34900535: 'STANDARD',
 34917753: 'GOLD',
 34931257: 'STANDARD',
 34975934: 'STANDARD',
 34996317: 'STANDARD',
 34996594: 'STANDARD',
 34998150: 'STANDARD',
 35006772: 'STANDARD',
 35007221: 'STANDARD',
 35014984: 'GOLD',
 35017309: 'STANDARD',
 35019240: 'STANDARD',
 35020545: 'STANDARD',
 35025301: 'STANDARD',
 35042338: 'STANDARD',
 35056426: 'STANDARD',
 35149256: 'STANDARD',
 35151240: 'STANDARD',
 35159557: 'STANDARD',
 35176518: 'STANDARD',
 35178555: 'STANDARD',
 35187462: 'GOLD',
 35194190: 'STANDARD',
 35276270: 'STANDARD',
 35297205: 'STANDARD',
 35335596: 'STANDARD',
 35349004: 'STANDARD',
 35354359: 'STANDARD',
 35372226: 'SILVER',
 35377989: 'STANDARD',
 35461466: 'DIAMOND',
 35465152: 'GOLD',
 35470932: 'STANDARD',
 35472274: 'STANDARD',
 35473482: 'STANDARD',
 35488880: 'STANDARD',
 35511908: 'STANDARD',
 35516548: 'STANDARD',
 35518790: 'STANDARD',
 35542868: 'STANDARD',
 35543442: 'STANDARD',
 35545828: 'STANDARD',
 35550789: 'SILVER',
 35629543: 'GOLD',
 35635482: 'STANDARD',
 35641635: 'SILVER',
 35656098: 'STANDARD',
 35688020: 'STANDARD',
 35703877: 'STANDARD',
 35709102: 'GOLD',
 35714690: 'STANDARD',
 35730005: 'STANDARD',
 35745039: 'STANDARD',
 35748645: 'STANDARD',
 35752260: 'STANDARD',
 35756036: 'STANDARD',
 35757825: 'GOLD',
 35758286: 'GOLD',
 35762627: 'STANDARD',
 35791329: 'SILVER',
 35804192: 'STANDARD',
 35813166: 'STANDARD',
 35817060: 'SILVER',
 35817610: 'STANDARD',
 35823449: 'STANDARD',
 35830645: 'STANDARD',
 35834143: 'STANDARD',
 35838999: 'STANDARD',
 35839355: 'STANDARD',
 35841509: 'STANDARD',
 35848172: 'STANDARD',
 35854663: 'STANDARD',
 35861877: 'STANDARD',
 35873781: 'STANDARD',
 35882656: 'STANDARD',
 35911895: 'SILVER',
 35917172: 'STANDARD',
 35919454: 'SILVER',
 35928802: 'STANDARD',
 35931383: 'SILVER',
 35947499: 'STANDARD',
 35991237: 'STANDARD',
 36005388: 'DIAMOND',
 36040051: 'STANDARD',
 36051609: 'STANDARD',
 36067366: 'STANDARD',
 36073416: 'STANDARD',
 36092565: 'STANDARD',
 36115314: 'GOLD',
 36123888: 'STANDARD',
 36133936: 'STANDARD',
 36164668: 'SILVER',
 36171958: 'STANDARD',
 36181574: 'STANDARD',
 36183959: 'STANDARD',
 36197931: 'STANDARD',
 36201652: 'STANDARD',
 36207639: 'STANDARD',
 36208284: 'STANDARD',
 36211134: 'STANDARD',
 36211732: 'STANDARD',
 36246504: 'STANDARD',
 36256038: 'STANDARD',
 36352628: 'STANDARD',
 36378675: 'STANDARD',
 36387014: 'STANDARD',
 36389921: 'STANDARD',
 36402949: 'STANDARD',
 36407771: 'SILVER',
 36415344: 'STANDARD',
 36448405: 'STANDARD',
 36473174: 'SILVER',
 36473511: 'GOLD',
 36476473: 'STANDARD',
 36486289: 'STANDARD',
 36510732: 'STANDARD',
 36518569: 'STANDARD',
 36519278: 'STANDARD',
 36538660: 'SILVER',
 36540260: 'STANDARD',
 36568868: 'STANDARD',
 36575147: 'STANDARD',
 36581970: 'STANDARD',
 36582414: 'STANDARD',
 36584838: 'SILVER',
 36592398: 'SILVER',
 36599793: 'STANDARD',
 36617308: 'SILVER',
 36629305: 'STANDARD',
 36631018: 'SILVER',
 36631215: 'STANDARD',
 36634633: 'STANDARD',
 36655220: 'STANDARD',
 36658409: 'SILVER',
 36658575: 'STANDARD',
 36674124: 'GOLD',
 36676324: 'SILVER',
 36689783: 'STANDARD',
 36692396: 'STANDARD',
 36699094: 'SILVER',
 36715574: 'STANDARD',
 36717354: 'STANDARD',
 36722085: 'STANDARD',
 36722103: 'STANDARD',
 36745329: 'STANDARD',
 36768597: 'SILVER',
 36777240: 'STANDARD',
 36809356: 'STANDARD',
 36828462: 'STANDARD',
 36841478: 'GOLD',
 36856721: 'STANDARD',
 36866173: 'STANDARD',
 36873195: 'STANDARD',
 36884902: 'GOLD',
 36897727: 'SILVER',
 36902617: 'STANDARD',
 36923890: 'STANDARD',
 36976220: 'STANDARD',
 37004993: 'STANDARD',
 37008898: 'GOLD',
 37019950: 'STANDARD',

In [128]:
df.Rank_name = df.User_id.map(data_dict)

In [129]:
df.head(20)

,DATE,Order_id,NEWVERTICAL_Merchant,MerchantID,User_id,GMV,Service Group,Loyalty Points,Rank_name,$cashback
0,2022-02-01,20510379115,Airtime,30,32983630,14000,data,140,STANDARD,NaN
1,2022-02-01,20514342785,Airtime,30,3560552,10000,data,100,SILVER,NaN
2,2022-02-01,20502357355,Airtime,30,52261329,28000,data,280,STANDARD,NaN
3,2022-02-01,20514894447,Airtime,30,45221505,20000,data,200,STANDARD,NaN
4,2022-02-01,20498110250,Airtime,30,32983630,5000,data,50,STANDARD,NaN
5,2022-02-01,20502643321,Airtime,30,39287223,84000,data,840,GOLD,NaN
6,2022-02-01,20517044473,Airtime,30,44349270,10000,data,100,STANDARD,NaN
7,2022-02-01,20480980421,Airtime,30,33686280,28000,data,280,STANDARD,NaN
8,2022-02-01,20509299182,Airtime,30,28057457,10000,data,100,SILVER,NaN
9,2022-02-01,20513652580,Airtime,30,45636816,10000,data,100,SILVER,NaN
10,2022-02-01,20517600545,Airtime,30,51338316,28000,data,280,STANDARD,NaN
11,2022-02-01,20518883833,Airtime,30,41627135,10000,data,100,STANDARD,NaN
12,2022-02-01,20482155098,Airtime,30,28151813,1000,data,10,STANDARD,NaN
13,2022-02-01,20516551995,Airtime,30,48567360,10000,data,100,STANDARD,NaN
14,2022-02-01,20513029925,Airtime,30,49316772,14000,data,140,STANDARD,NaN
15,2022-02-01,20502638879,Airtime,30,35635482,14000,data,140,STANDARD,NaN
16,2022-02-01,20519032549,Airtime,43,52158490,20000,data,200,STANDARD,NaN
17,2022-02-01,20503568768,Airtime,43,15886868,20000,data,200,STANDARD,NaN
18,2022-02-01,20508588805,Airtime,43,46740171,1000,data,10,GOLD,NaN
19,2022-02-01,20519033109,Airtime,43,52158490,13000,data,130,STANDARD,NaN

#### Calculate cashback cost for each Transaction

In [132]:
for i in range(len(df)):
    #if df["Rank_name"][i] == "STANDARD":
    #    df.cashback = 0
    if df["Rank_name"][i] == "SILVER":
        if df["Service Group"][i] == "cvs":
            df["$cashback"][i] = df["GMV"][i] * 0.05
        elif df["Service Group"][i] == "Offline Beverage":
            df["$cashback"][i] = df["GMV"][i] * 0.05
        elif df["Service Group"][i] == "data":
            df["$cashback"][i] = df["GMV"][i] * 0.05
        else:
            df["$cashback"][i] = 0
    elif df["Rank_name"][i] == "GOLD":
        if df["Service Group"][i] == "cvs":
            df["$cashback"][i] = df["GMV"][i] * 0.07
        elif df["Service Group"][i] == "Offline Beverage":
            df["$cashback"][i] = df["GMV"][i] * 0.07
        elif df["Service Group"][i] == "data":
            df["$cashback"][i] = df["GMV"][i] * 0.07
        elif df["Service Group"][i] == "marketplace":
            df["$cashback"][i] = df["GMV"][i] * 0.02
        elif df["Service Group"][i] == "supermarket":
            df["$cashback"][i] = df["GMV"][i] * 0.02
        else:
            df["$cashback"][i] = 0
    elif df["Rank_name"][i] == "DIAMOND":
        if df["Service Group"][i] == "cvs":
            df["$cashback"][i] = df["GMV"][i] * 0.12
        if df["Service Group"][i] == "Offline Beverage":
            df["$cashback"][i] = df["GMV"][i] * 0.12
        if df["Service Group"][i] == "data":
            df["$cashback"][i] = df["GMV"][i] * 0.12
        if df["Service Group"][i] == "marketplace":
            df["$cashback"][i] = df["GMV"][i] * 0.05
        if df["Service Group"][i] == "supermarket":
            df["$cashback"][i] = df["GMV"][i] * 0.05
        else:
            df["$cashback"][i] = 0
    else:
        df["$cashback"][i] = 0

<ipython-input-132-a3bfb505b6f2>:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["$cashback"][i] = 0
<ipython-input-132-a3bfb505b6f2>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["$cashback"][i] = df["GMV"][i] * 0.05
<ipython-input-132-a3bfb505b6f2>:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["$cashback"][i] = df["GMV"][i] * 0.07
<ipython-input-132-a3bfb505b6f2>:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["$cashback"][i] = df["GMV"][i] * 0.07
<ipython-input-132-a3bfb505b6f2>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["$cashback"][i] = df["GMV"][i] * 0.05
<ipython-input-132-a3bfb505b6f2>:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["$cashback"][i] = 0
<ipython-input-132-a3bfb505b6f2>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["$cashback"][i] = 0
<ipython-input-132-a3bfb505b6f2>:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["$cashback"][i] = df["GMV"][i] * 0.05
<ipython-input-132-a3bfb505b6f2>:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["$cashback"][i] = df["GMV"][i] * 0.02
<ipython-input-132-a3bfb505b6f2>:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["$cashback"][i] = 0
<ipython-input-132-a3bfb505b6f2>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["$cashback"][i] = df["GMV"][i] * 0.02
<ipython-input-132-a3bfb505b6f2>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["$cashback"][i] = df["GMV"][i] * 0.12
<ipython-input-132-a3bfb505b6f2>:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["$cashback"][i] = df["GMV"][i] * 0.12
<ipython-input-132-a3bfb505b6f2>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["$cashback"][i] = df["GMV"][i] * 0.05
<ipython-input-132-a3bfb505b6f2>:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["$cashback"][i] = df["GMV"][i] * 0.05
<ipython-input-132-a3bfb505b6f2>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["$cashback"][i] = df["GMV"][i] * 0.07

In [135]:
df["$cashback"].isnull().values.any()

False

In [137]:
df["$cashback"]= df["$cashback"].astype("int")

In [138]:
df.head(20)

,DATE,Order_id,NEWVERTICAL_Merchant,MerchantID,User_id,GMV,Service Group,Loyalty Points,Rank_name,$cashback
0,2022-02-01,20510379115,Airtime,30,32983630,14000,data,140,STANDARD,0
1,2022-02-01,20514342785,Airtime,30,3560552,10000,data,100,SILVER,500
2,2022-02-01,20502357355,Airtime,30,52261329,28000,data,280,STANDARD,0
3,2022-02-01,20514894447,Airtime,30,45221505,20000,data,200,STANDARD,0
4,2022-02-01,20498110250,Airtime,30,32983630,5000,data,50,STANDARD,0
5,2022-02-01,20502643321,Airtime,30,39287223,84000,data,840,GOLD,5880
6,2022-02-01,20517044473,Airtime,30,44349270,10000,data,100,STANDARD,0
7,2022-02-01,20480980421,Airtime,30,33686280,28000,data,280,STANDARD,0
8,2022-02-01,20509299182,Airtime,30,28057457,10000,data,100,SILVER,500
9,2022-02-01,20513652580,Airtime,30,45636816,10000,data,100,SILVER,500
10,2022-02-01,20517600545,Airtime,30,51338316,28000,data,280,STANDARD,0
11,2022-02-01,20518883833,Airtime,30,41627135,10000,data,100,STANDARD,0
12,2022-02-01,20482155098,Airtime,30,28151813,1000,data,10,STANDARD,0
13,2022-02-01,20516551995,Airtime,30,48567360,10000,data,100,STANDARD,0
14,2022-02-01,20513029925,Airtime,30,49316772,14000,data,140,STANDARD,0
15,2022-02-01,20502638879,Airtime,30,35635482,14000,data,140,STANDARD,0
16,2022-02-01,20519032549,Airtime,43,52158490,20000,data,200,STANDARD,0
17,2022-02-01,20503568768,Airtime,43,15886868,20000,data,200,STANDARD,0
18,2022-02-01,20508588805,Airtime,43,46740171,1000,data,10,GOLD,70
19,2022-02-01,20519033109,Airtime,43,52158490,13000,data,130,STANDARD,0

In [140]:
for i in range(len(df)):
    if df["$cashback"][i] > 10000:
        df["$cashback"][i] = 10000

In [141]:
df.to_excel("Final3.xlsx")